services:
  backend:
    image: rails-monolith
    build:
      context: .
      dockerfile: development.Dockerfile
    depends_on:
      - frontend
    volumes:
      - .:/app
    ports:
      - 3000:3000
    env_file: .env.development
  frontend:
    image: vite
    build:
      context: .
      dockerfile: vite.Dockerfile
    env_file: .env.development
    ports:
      - 5173:5173
    volumes:
      - .:/app
